pages:
  stage: deploy
  image: node:20
  script:
    - npm install
    - npm run build
  publish: dist
  artifacts:
    paths:
      - dist
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
